version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    volumes:
    - ~/data/docker/compose/nacos-promtheus-grafana/standalone-logs/:/home/nacos/logs
    - ~/work/docker/compose/nacos-promtheus-grafana/init.d/custom.properties:/home/nacos/init.d/custom.properties
    - ~/work/docker/compose/nacos-promtheus-grafana/nacos/data:/home/nacos/data
    ports:
    - "8848:8848"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ~/work/docker/compose/nacos-promtheus-grafana/init.d/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: on-failure
